language: python
os: linux

matrix:

  include:
  - env: PYTHON_VERSION="3.4"
  - env: PYTHON_VERSION="3.5"


cache:
  directories:
    - $HOME/.cache/pip
  pip: true

sudo: false

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if [[ `which conda` ]]; then echo 'Conda installation successful'; else exit 1; fi
  - conda update --yes conda
  - conda create -n testenv --yes python=$PYTHON_VERSION pip wheel nose
  - source activate testenv
  - conda install --yes gcc
  - echo "Using GCC at "`which gcc`
  - export CC=`which gcc`

install:
  - pip install coverage pep8 python-coveralls
  - cat requirements.txt | xargs -n 1 -L 1 pip install
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - nosetests -sv --with-coverage --cover-package=hpolib
after_success:
  - coveralls
